### PR TITLE
Fyndor#1 testing out linking issues

### PR DESCRIPTION
**Pull request by fyndor**
So will this auto link the issues

### CODE REVIEW

**Comment by fyndor** [comment]
Doh.  How bout saying this is for issue #1

**Comment by fyndor** [comment]
Hmm so it works in the comments ok  :+1:

**Comment by atticoos** [comment]
If you type "Closes #1" or "Fixes #1", it should automatically close the issue when this merges too

**Comment by fyndor** [comment]
Thanks for the tip

**Pull request merged**
